# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Pass - Sponsorship (47bfb371-2f3f-4972-a903-e9dadd96af7b)'
    subscriptionId: '47bfb371-2f3f-4972-a903-e9dadd96af7b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'JacobRG'
    location: 'UK South'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://dev.azure.com/millionlightssj/Jacob-Project/_git/ARMTemplateDeploy?path=%2FStorageAccountTemplate.json'
    deploymentMode: 'Incremental'

